name: check-size

on: pull_request

jobs:
  check-size:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.13, 14.15, 16.14, 18.12]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node 14.15
        uses: actions/setup-node@v3
        with:
          node-version: 14.15

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Complete Buildx Setup
        run:  docker run --privileged --rm tonistiigi/binfmt --install all

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore node modules from cache
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Build Layers
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: ./scripts/build_layers.sh

      - name: Check Size
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: ./scripts/check_layer_size.sh
